/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMyAppsRouteImport } from './routes/_authenticated/my-apps'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as AppsSlugRouteImport } from './routes/apps.$slug'
import { Route as GiftSlugRouteImport } from './routes/gift.$slug'
import { Route as AuthenticatedCheckoutSlugRouteImport } from './routes/_authenticated/checkout.$slug'
import { Route as AuthenticatedRedeemTokenRouteImport } from './routes/_authenticated/redeem.$token'
import { Route as AuthenticatedAppFameOFameIndexRouteImport } from './routes/_authenticated/app.fame-o-fame.index'
import { Route as AuthenticatedAppFameOFameExercisesRouteImport } from './routes/_authenticated/app.fame-o-fame.exercises'
import { Route as AuthenticatedAppFameOFameMonthlyRouteImport } from './routes/_authenticated/app.fame-o-fame.monthly'
import { Route as AuthenticatedAppFameOFameOnboardingRouteImport } from './routes/_authenticated/app.fame-o-fame.onboarding'
import { Route as AuthenticatedAppFameOFameReportRouteImport } from './routes/_authenticated/app.fame-o-fame.report'
import { Route as AuthenticatedAppFameOFameSettingsRouteImport } from './routes/_authenticated/app.fame-o-fame.settings'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAppsRoute = AuthenticatedMyAppsRouteImport.update({
  id: '/my-apps',
  path: '/my-apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftSlugRoute = GiftSlugRouteImport.update({
  id: '/gift/$slug',
  path: '/gift/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutSlugRoute =
  AuthenticatedCheckoutSlugRouteImport.update({
    id: '/checkout/$slug',
    path: '/checkout/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedeemTokenRoute =
  AuthenticatedRedeemTokenRouteImport.update({
    id: '/redeem/$token',
    path: '/redeem/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFameOFameIndexRoute =
  AuthenticatedAppFameOFameIndexRouteImport.update({
    id: '/app/fame-o-fame/',
    path: '/app/fame-o-fame/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFameOFameExercisesRoute =
  AuthenticatedAppFameOFameExercisesRouteImport.update({
    id: '/app/fame-o-fame/exercises',
    path: '/app/fame-o-fame/exercises',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFameOFameMonthlyRoute =
  AuthenticatedAppFameOFameMonthlyRouteImport.update({
    id: '/app/fame-o-fame/monthly',
    path: '/app/fame-o-fame/monthly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFameOFameOnboardingRoute =
  AuthenticatedAppFameOFameOnboardingRouteImport.update({
    id: '/app/fame-o-fame/onboarding',
    path: '/app/fame-o-fame/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFameOFameReportRoute =
  AuthenticatedAppFameOFameReportRouteImport.update({
    id: '/app/fame-o-fame/report',
    path: '/app/fame-o-fame/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFameOFameSettingsRoute =
  AuthenticatedAppFameOFameSettingsRouteImport.update({
    id: '/app/fame-o-fame/settings',
    path: '/app/fame-o-fame/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-apps': typeof AuthenticatedMyAppsRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/gift/$slug': typeof GiftSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/checkout/$slug': typeof AuthenticatedCheckoutSlugRoute
  '/redeem/$token': typeof AuthenticatedRedeemTokenRoute
  '/app/fame-o-fame/exercises': typeof AuthenticatedAppFameOFameExercisesRoute
  '/app/fame-o-fame/monthly': typeof AuthenticatedAppFameOFameMonthlyRoute
  '/app/fame-o-fame/onboarding': typeof AuthenticatedAppFameOFameOnboardingRoute
  '/app/fame-o-fame/report': typeof AuthenticatedAppFameOFameReportRoute
  '/app/fame-o-fame/settings': typeof AuthenticatedAppFameOFameSettingsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/fame-o-fame/': typeof AuthenticatedAppFameOFameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-apps': typeof AuthenticatedMyAppsRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/gift/$slug': typeof GiftSlugRoute
  '/apps': typeof AppsIndexRoute
  '/checkout/$slug': typeof AuthenticatedCheckoutSlugRoute
  '/redeem/$token': typeof AuthenticatedRedeemTokenRoute
  '/app/fame-o-fame/exercises': typeof AuthenticatedAppFameOFameExercisesRoute
  '/app/fame-o-fame/monthly': typeof AuthenticatedAppFameOFameMonthlyRoute
  '/app/fame-o-fame/onboarding': typeof AuthenticatedAppFameOFameOnboardingRoute
  '/app/fame-o-fame/report': typeof AuthenticatedAppFameOFameReportRoute
  '/app/fame-o-fame/settings': typeof AuthenticatedAppFameOFameSettingsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/fame-o-fame': typeof AuthenticatedAppFameOFameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/my-apps': typeof AuthenticatedMyAppsRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/gift/$slug': typeof GiftSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/_authenticated/checkout/$slug': typeof AuthenticatedCheckoutSlugRoute
  '/_authenticated/redeem/$token': typeof AuthenticatedRedeemTokenRoute
  '/_authenticated/app/fame-o-fame/exercises': typeof AuthenticatedAppFameOFameExercisesRoute
  '/_authenticated/app/fame-o-fame/monthly': typeof AuthenticatedAppFameOFameMonthlyRoute
  '/_authenticated/app/fame-o-fame/onboarding': typeof AuthenticatedAppFameOFameOnboardingRoute
  '/_authenticated/app/fame-o-fame/report': typeof AuthenticatedAppFameOFameReportRoute
  '/_authenticated/app/fame-o-fame/settings': typeof AuthenticatedAppFameOFameSettingsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/app/fame-o-fame/': typeof AuthenticatedAppFameOFameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/faq'
    | '/account'
    | '/admin'
    | '/my-apps'
    | '/apps/$slug'
    | '/gift/$slug'
    | '/apps/'
    | '/checkout/$slug'
    | '/redeem/$token'
    | '/app/fame-o-fame/exercises'
    | '/app/fame-o-fame/monthly'
    | '/app/fame-o-fame/onboarding'
    | '/app/fame-o-fame/report'
    | '/app/fame-o-fame/settings'
    | '/api/public/payments/webhook'
    | '/app/fame-o-fame/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/faq'
    | '/account'
    | '/admin'
    | '/my-apps'
    | '/apps/$slug'
    | '/gift/$slug'
    | '/apps'
    | '/checkout/$slug'
    | '/redeem/$token'
    | '/app/fame-o-fame/exercises'
    | '/app/fame-o-fame/monthly'
    | '/app/fame-o-fame/onboarding'
    | '/app/fame-o-fame/report'
    | '/app/fame-o-fame/settings'
    | '/api/public/payments/webhook'
    | '/app/fame-o-fame'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/faq'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/my-apps'
    | '/apps/$slug'
    | '/gift/$slug'
    | '/apps/'
    | '/_authenticated/checkout/$slug'
    | '/_authenticated/redeem/$token'
    | '/_authenticated/app/fame-o-fame/exercises'
    | '/_authenticated/app/fame-o-fame/monthly'
    | '/_authenticated/app/fame-o-fame/onboarding'
    | '/_authenticated/app/fame-o-fame/report'
    | '/_authenticated/app/fame-o-fame/settings'
    | '/api/public/payments/webhook'
    | '/_authenticated/app/fame-o-fame/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  AppsSlugRoute: typeof AppsSlugRoute
  GiftSlugRoute: typeof GiftSlugRoute
  AppsIndexRoute: typeof AppsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-apps': {
      id: '/_authenticated/my-apps'
      path: '/my-apps'
      fullPath: '/my-apps'
      preLoaderRoute: typeof AuthenticatedMyAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/$slug': {
      id: '/gift/$slug'
      path: '/gift/$slug'
      fullPath: '/gift/$slug'
      preLoaderRoute: typeof GiftSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout/$slug': {
      id: '/_authenticated/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof AuthenticatedCheckoutSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redeem/$token': {
      id: '/_authenticated/redeem/$token'
      path: '/redeem/$token'
      fullPath: '/redeem/$token'
      preLoaderRoute: typeof AuthenticatedRedeemTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/fame-o-fame/': {
      id: '/_authenticated/app/fame-o-fame/'
      path: '/app/fame-o-fame'
      fullPath: '/app/fame-o-fame/'
      preLoaderRoute: typeof AuthenticatedAppFameOFameIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/fame-o-fame/exercises': {
      id: '/_authenticated/app/fame-o-fame/exercises'
      path: '/app/fame-o-fame/exercises'
      fullPath: '/app/fame-o-fame/exercises'
      preLoaderRoute: typeof AuthenticatedAppFameOFameExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/fame-o-fame/monthly': {
      id: '/_authenticated/app/fame-o-fame/monthly'
      path: '/app/fame-o-fame/monthly'
      fullPath: '/app/fame-o-fame/monthly'
      preLoaderRoute: typeof AuthenticatedAppFameOFameMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/fame-o-fame/onboarding': {
      id: '/_authenticated/app/fame-o-fame/onboarding'
      path: '/app/fame-o-fame/onboarding'
      fullPath: '/app/fame-o-fame/onboarding'
      preLoaderRoute: typeof AuthenticatedAppFameOFameOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/fame-o-fame/report': {
      id: '/_authenticated/app/fame-o-fame/report'
      path: '/app/fame-o-fame/report'
      fullPath: '/app/fame-o-fame/report'
      preLoaderRoute: typeof AuthenticatedAppFameOFameReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/fame-o-fame/settings': {
      id: '/_authenticated/app/fame-o-fame/settings'
      path: '/app/fame-o-fame/settings'
      fullPath: '/app/fame-o-fame/settings'
      preLoaderRoute: typeof AuthenticatedAppFameOFameSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMyAppsRoute: typeof AuthenticatedMyAppsRoute
  AuthenticatedCheckoutSlugRoute: typeof AuthenticatedCheckoutSlugRoute
  AuthenticatedRedeemTokenRoute: typeof AuthenticatedRedeemTokenRoute
  AuthenticatedAppFameOFameExercisesRoute: typeof AuthenticatedAppFameOFameExercisesRoute
  AuthenticatedAppFameOFameMonthlyRoute: typeof AuthenticatedAppFameOFameMonthlyRoute
  AuthenticatedAppFameOFameOnboardingRoute: typeof AuthenticatedAppFameOFameOnboardingRoute
  AuthenticatedAppFameOFameReportRoute: typeof AuthenticatedAppFameOFameReportRoute
  AuthenticatedAppFameOFameSettingsRoute: typeof AuthenticatedAppFameOFameSettingsRoute
  AuthenticatedAppFameOFameIndexRoute: typeof AuthenticatedAppFameOFameIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMyAppsRoute: AuthenticatedMyAppsRoute,
  AuthenticatedCheckoutSlugRoute: AuthenticatedCheckoutSlugRoute,
  AuthenticatedRedeemTokenRoute: AuthenticatedRedeemTokenRoute,
  AuthenticatedAppFameOFameExercisesRoute:
    AuthenticatedAppFameOFameExercisesRoute,
  AuthenticatedAppFameOFameMonthlyRoute: AuthenticatedAppFameOFameMonthlyRoute,
  AuthenticatedAppFameOFameOnboardingRoute:
    AuthenticatedAppFameOFameOnboardingRoute,
  AuthenticatedAppFameOFameReportRoute: AuthenticatedAppFameOFameReportRoute,
  AuthenticatedAppFameOFameSettingsRoute:
    AuthenticatedAppFameOFameSettingsRoute,
  AuthenticatedAppFameOFameIndexRoute: AuthenticatedAppFameOFameIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  AppsSlugRoute: AppsSlugRoute,
  GiftSlugRoute: GiftSlugRoute,
  AppsIndexRoute: AppsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
