/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMyAppsRouteImport } from './routes/_authenticated/my-apps'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as AppsSlugRouteImport } from './routes/apps.$slug'
import { Route as GiftSlugRouteImport } from './routes/gift.$slug'
import { Route as AuthenticatedAppSplatRouteImport } from './routes/_authenticated/app.$'
import { Route as AuthenticatedCheckoutSlugRouteImport } from './routes/_authenticated/checkout.$slug'
import { Route as AuthenticatedRedeemTokenRouteImport } from './routes/_authenticated/redeem.$token'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAppsRoute = AuthenticatedMyAppsRouteImport.update({
  id: '/my-apps',
  path: '/my-apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftSlugRoute = GiftSlugRouteImport.update({
  id: '/gift/$slug',
  path: '/gift/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSplatRoute = AuthenticatedAppSplatRouteImport.update({
  id: '/app/$',
  path: '/app/$',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutSlugRoute =
  AuthenticatedCheckoutSlugRouteImport.update({
    id: '/checkout/$slug',
    path: '/checkout/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedeemTokenRoute =
  AuthenticatedRedeemTokenRouteImport.update({
    id: '/redeem/$token',
    path: '/redeem/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suggest': typeof SuggestRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-apps': typeof AuthenticatedMyAppsRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/gift/$slug': typeof GiftSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/app/$': typeof AuthenticatedAppSplatRoute
  '/checkout/$slug': typeof AuthenticatedCheckoutSlugRoute
  '/redeem/$token': typeof AuthenticatedRedeemTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suggest': typeof SuggestRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-apps': typeof AuthenticatedMyAppsRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/gift/$slug': typeof GiftSlugRoute
  '/apps': typeof AppsIndexRoute
  '/app/$': typeof AuthenticatedAppSplatRoute
  '/checkout/$slug': typeof AuthenticatedCheckoutSlugRoute
  '/redeem/$token': typeof AuthenticatedRedeemTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suggest': typeof SuggestRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/my-apps': typeof AuthenticatedMyAppsRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/gift/$slug': typeof GiftSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/_authenticated/app/$': typeof AuthenticatedAppSplatRoute
  '/_authenticated/checkout/$slug': typeof AuthenticatedCheckoutSlugRoute
  '/_authenticated/redeem/$token': typeof AuthenticatedRedeemTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/faq'
    | '/reset-password'
    | '/suggest'
    | '/account'
    | '/admin'
    | '/my-apps'
    | '/apps/$slug'
    | '/gift/$slug'
    | '/apps/'
    | '/app/$'
    | '/checkout/$slug'
    | '/redeem/$token'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/faq'
    | '/reset-password'
    | '/suggest'
    | '/account'
    | '/admin'
    | '/my-apps'
    | '/apps/$slug'
    | '/gift/$slug'
    | '/apps'
    | '/app/$'
    | '/checkout/$slug'
    | '/redeem/$token'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/faq'
    | '/reset-password'
    | '/suggest'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/my-apps'
    | '/apps/$slug'
    | '/gift/$slug'
    | '/apps/'
    | '/_authenticated/app/$'
    | '/_authenticated/checkout/$slug'
    | '/_authenticated/redeem/$token'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuggestRoute: typeof SuggestRoute
  AppsSlugRoute: typeof AppsSlugRoute
  GiftSlugRoute: typeof GiftSlugRoute
  AppsIndexRoute: typeof AppsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-apps': {
      id: '/_authenticated/my-apps'
      path: '/my-apps'
      fullPath: '/my-apps'
      preLoaderRoute: typeof AuthenticatedMyAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/$slug': {
      id: '/gift/$slug'
      path: '/gift/$slug'
      fullPath: '/gift/$slug'
      preLoaderRoute: typeof GiftSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/$': {
      id: '/_authenticated/app/$'
      path: '/app/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AuthenticatedAppSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$slug': {
      id: '/_authenticated/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof AuthenticatedCheckoutSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redeem/$token': {
      id: '/_authenticated/redeem/$token'
      path: '/redeem/$token'
      fullPath: '/redeem/$token'
      preLoaderRoute: typeof AuthenticatedRedeemTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMyAppsRoute: typeof AuthenticatedMyAppsRoute
  AuthenticatedAppSplatRoute: typeof AuthenticatedAppSplatRoute
  AuthenticatedCheckoutSlugRoute: typeof AuthenticatedCheckoutSlugRoute
  AuthenticatedRedeemTokenRoute: typeof AuthenticatedRedeemTokenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMyAppsRoute: AuthenticatedMyAppsRoute,
  AuthenticatedAppSplatRoute: AuthenticatedAppSplatRoute,
  AuthenticatedCheckoutSlugRoute: AuthenticatedCheckoutSlugRoute,
  AuthenticatedRedeemTokenRoute: AuthenticatedRedeemTokenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuggestRoute: SuggestRoute,
  AppsSlugRoute: AppsSlugRoute,
  GiftSlugRoute: GiftSlugRoute,
  AppsIndexRoute: AppsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
